# Generated by Django 5.0.6 on 2024-07-14 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('IND', 'INDIA'), ('JAP', 'JAPAN'), ('AUS', 'Australia'), ('ENG', 'England'), ('USA', 'United States of America')], default='IND', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='ChaiVariety',
        ),
    ]
