# Generated by Django 5.0.6 on 2024-07-14 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_countries_delete_chaivariety'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='type',
            new_name='country',
        ),
        migrations.AddField(
            model_name='countries',
            name='capital',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
